// Auto-generated by tauri-specta — do not edit manually
//
// This file bridges Rust types (with specta::Type derive) to TypeScript.
// Rust types are defined in src-tauri/src/database/models.rs, error.rs, config.rs,
// and services/download/mod.rs.
//
// To regenerate: run `cargo build` in src-tauri/ (requires specta::Type derives on Rust types).

// ============================================================
// 配置类型（对齐 Rust config::AppConfig）
// ============================================================

export interface AppConfig {
  cookie: string;
  download_path: string;
  naming: string;
  encryption: string;
  proxy: string;
  app_name: string;
  folderize: boolean;
  music: boolean;
  cover: boolean;
  desc: boolean;
  interval: string | null;
  page_counts: number;
  max_counts: number;
  timeout: number;
  max_connections: number;
  max_retries: number;
  max_tasks: number;
}

// ============================================================
// 错误类型（对齐 Rust error::ErrorCode + AppError）
// ============================================================

export type ErrorCode =
  | "network_timeout"
  | "network_error"
  | "rate_limited"
  | "proxy_error"
  | "cookie_expired"
  | "cookie_invalid"
  | "login_required"
  | "video_not_found"
  | "user_not_found"
  | "content_deleted"
  | "signature_error"
  | "parse_error"
  | "database_error"
  | "file_system_error"
  | "config_error"
  | "unknown";

export interface AppError {
  code: ErrorCode;
  message: string;
  detail?: string;
}

// ============================================================
// 数据库模型（对齐 Rust database::models）
// ============================================================

export interface LiveRecord {
  id: number;
  room_id: string | null;
  web_rid: string | null;
  title: string | null;
  nickname: string | null;
  sec_user_id: string | null;
  file_path: string | null;
  file_size: number;
  duration_sec: number;
  status: string;
  started_at: number | null;
  ended_at: number | null;
  cover_url: string | null;
}

export interface DownloadTask {
  id: string;
  mode: string;
  url: string;
  title: string | null;
  author_nickname: string | null;
  status: string;
  total: number;
  completed: number;
  skipped: number;
  failed: number;
  error_msg: string | null;
  created_at: number;
  updated_at: number;
}

export interface TaskItem {
  id: number;
  task_id: string;
  aweme_id: string | null;
  media_key: string | null;
  media_kind: string | null;
  media_index: number | null;
  title: string | null;
  author_nickname: string | null;
  author_sec_uid: string | null;
  cover_url: string | null;
  file_path: string | null;
  file_size: number;
  status: string;
  error_msg: string | null;
  created_at: number;
}

export interface TaskItemCounts {
  total: number;
  completed: number;
  skipped: number;
  failed: number;
  pending: number;
}

export interface DownloadTaskDetail {
  task: DownloadTask;
  items: TaskItem[];
}

export interface UserInfo {
  sec_user_id: string;
  nickname: string | null;
  uid: string | null;
  avatar_url: string | null;
  unique_id: string | null;
  signature: string | null;
  aweme_count: number;
  follower_count: number;
  following_count: number;
  total_favorited: number;
  ip_location: string | null;
  live_status: number;
  room_id: string | null;
  city: string | null;
  country: string | null;
  favoriting_count: number;
  gender: number;
  is_ban: number;
  is_block: number;
  is_blocked: number;
  is_star: number;
  mix_count: number;
  mplatform_followers_count: number;
  nickname_raw: string | null;
  school_name: string | null;
  short_id: string | null;
  signature_raw: string | null;
  user_age: number;
  custom_verify: string | null;
  updated_at: number;
}

export interface VideoInfo {
  aweme_id: string;
  desc: string | null;
  aweme_type: number;
  author_nickname: string | null;
  author_sec_uid: string | null;
  author_uid: string | null;
  create_time: number | null;
  duration: number;
  video_url: string | null;
  cover_url: string | null;
  music_title: string | null;
  digg_count: number;
  comment_count: number;
  share_count: number;
  collect_count: number;
  mix_id: string | null;
  mix_name: string | null;
  updated_at: number;
}

export interface VideoTypeStat {
  aweme_type: number;
  cnt: number;
}

export interface VideoStats {
  total_count: number;
  total_digg: number;
  total_comment: number;
  total_share: number;
  total_collect: number;
  by_type: VideoTypeStat[];
}

export interface UserStats {
  total_count: number;
  total_follower: number;
  total_aweme: number;
}

export interface TrendPoint {
  day: string;
  cnt: number;
  size: number;
}

export interface AuthorStat {
  author_nickname: string;
  cnt: number;
  total_size: number;
}

export interface StorageStat {
  download_type: string;
  cnt: number;
  total_size: number;
}

export interface DbHealth {
  video_count: number;
  user_count: number;
  live_count: number;
  music_count: number;
  task_count: number;
  db_size_bytes: number;
}

export interface MusicCollection {
  music_id: string;
  mid: string | null;
  title: string | null;
  author: string | null;
  owner_nickname: string | null;
  duration: number;
  cover: string | null;
  play_url: string | null;
  file_path: string | null;
  status: string;
  created_at: number;
}

// ============================================================
// 下载服务类型（对齐 Rust services::download）
// ============================================================

export type DownloadMode = "one" | "post" | "like" | "mix" | "collects" | "live" | "music";

export type TaskStatus = "pending" | "starting" | "running" | "recording" | "stopping" | "completed" | "error" | "cancelled" | "interrupted";

export type TaskEventType = "started" | "progress" | "finished";

export interface TaskPatch {
  task_id: string;
  status?: TaskStatus;
  total?: number;
  completed?: number;
  skipped?: number;
  failed?: number;
  error_msg?: string;
  current_item?: string;
  title?: string;
  nickname?: string;
  room_id?: string;
  web_rid?: string;
  cover_url?: string;
  file?: string;
  file_size?: number;
  duration_sec?: number;
  started_at?: number;
  ended_at?: number;
}

export interface TaskEvent {
  event_type: TaskEventType;
  task_id: string;
  mode?: DownloadMode;
  url?: string;
  patch: TaskPatch;
}
